services:
  app:
    environment:
      BLACKCAT_TESTING_TAMPER_AFTER_SEC: "0"
      BLACKCAT_TESTING_RPC_SABOTAGE_AFTER_SEC: "0"
      BLACKCAT_TESTING_LOCAL_RPC_PROXY: "1"
      BLACKCAT_TESTING_RPC_PROXY_UPSTREAM: "https://rpc.layeredge.io"
      BLACKCAT_TESTING_RPC_PROXY_SABOTAGE_AFTER_SEC: "30"
      BLACKCAT_TRUST_RPC_ENDPOINTS: "https://rpc.layeredge.io,http://127.0.0.1:8545"
      BLACKCAT_TRUST_RPC_QUORUM: "2"

  attacker:
    environment:
      ATTACK_DURATION_SEC: "120"
      EXPECT_TRUST_OK_AT_START: "1"
      EXPECT_TRUST_FAIL_AFTER_TAMPER: "0"
      EXPECT_STALE_READS_ON_RPC_OUTAGE: "1"
